// <auto-generated />
using HomeKeep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeKeep.Migrations
{
    [DbContext(typeof(HomeKeepContext))]
    [Migration("20261001152317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeKeep.Models.MaintenanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FrequencyDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Replace the HVAC filter to maintain airflow and indoor air quality.",
                            FrequencyDays = 90,
                            IsCompleted = false,
                            Name = "Replace furnace filter",
                            Room = "Basement"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test each detector and replace weak or expired batteries.",
                            FrequencyDays = 30,
                            IsCompleted = true,
                            Name = "Test smoke detectors",
                            Room = "Entire Home"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Remove lint from the dryer vent and inspect the exhaust connection.",
                            FrequencyDays = 180,
                            IsCompleted = false,
                            Name = "Clean dryer vent",
                            Room = "Laundry Room"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Check supply lines, drains, and cabinet surfaces for signs of leaks.",
                            FrequencyDays = 90,
                            IsCompleted = false,
                            Name = "Inspect under-sink plumbing",
                            Room = "Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Remove dust from the refrigerator coils to improve efficiency.",
                            FrequencyDays = 180,
                            IsCompleted = true,
                            Name = "Clean refrigerator coils",
                            Room = "Kitchen"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Inspect the water heater and surrounding area for leaks or corrosion.",
                            FrequencyDays = 90,
                            IsCompleted = false,
                            Name = "Check water heater",
                            Room = "Basement"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
